services:
  web:
    build: "."
    ports:
      - "8080:8080"
    expose:
      - "8080"
    # environmental variables are set within the dockerfile
    depends_on: 
      - db
  db:
    image: "postgres:12.7"
    ports:
      - "5432:5432"
    env_file:
      - env.properties
    volumes:
      - ./create-all-tables.sql:/docker-entrypoint-initdb.d/init.sql
